# Generated by Django 6.0.6 on 2026-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of the Meal"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description of the Meal"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price($)"
                    ),
                ),
                ("available", models.BooleanField(default=False)),
            ],
        ),
    ]
