# Generated by Django 6.0.6 on 2026-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="available",
            field=models.BooleanField(
                default=False, verbose_name="Online Availability"
            ),
        ),
    ]
