# Generated by Django 6.0.6 on 2026-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_meal_stock_alter_meal_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="meal_images/default_meal_image.jpg", upload_to="meal_images"
            ),
        ),
    ]
