# Generated by Django 6.0.7 on 2026-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_ordertransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="category",
            field=models.CharField(default="Main Course", max_length=50),
        ),
        migrations.AddField(
            model_name="meal",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="preparation_time",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
