# Generated by Django 6.0.7 on 2026-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("UPI", "UPI"), ("CARD", "Card")],
                default="COD",
                max_length=10,
            ),
        ),
    ]
