# Generated by Django 6.0.7 on 2026-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_ordertransaction_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertransaction",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
