# Generated by Django 6.0.7 on 2026-07-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_ordertransaction_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("failed", "FAILED"),
                    ("completed", "COMPLETED"),
                ],
                default="Pending",
                max_length=9,
                verbose_name="Delivery Status",
            ),
        ),
    ]
