# Generated by Django 6.0.7 on 2026-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount", models.IntegerField(help_text="Discount Percentage")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.CharField(
                choices=[
                    ("Starter", "Starter"),
                    ("Main Course", "Main Course"),
                    ("Dessert", "Dessert"),
                    ("Drinks", "Drinks"),
                ],
                default="Main Course",
                max_length=20,
            ),
        ),
    ]
