# Generated by Django 6.0.7 on 2026-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_coupon_alter_meal_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.CharField(
                choices=[
                    ("Chinese", "Chinese"),
                    ("Main Course", "Main Course"),
                    ("South Indian", "South Indian"),
                ],
                default="Main Course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordertransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Preparing", "Preparing"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Delivery Status",
            ),
        ),
    ]
